# Generated by Django 4.0.3 on 2022-10-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_salescustomer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='name',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
