# Generated by Django 4.0.3 on 2022-10-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_name_automobilevo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='sales_price',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salescustomer',
            name='phone_number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrep',
            name='employee_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
