# Generated by Django 4.0.3 on 2022-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_salerecord_sales_price_salescustomer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescustomer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
