# Generated by Django 4.0.3 on 2022-10-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_salescustomer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
