# Generated by Django 4.0.3 on 2022-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_alter_salesrep_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
