# Generated by Django 4.0.3 on 2022-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_salesrep_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
