# Generated by Django 4.0.3 on 2022-10-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_automobilevo_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='in_stock',
        ),
    ]
