# Generated by Django 4.0.3 on 2022-10-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_automobilevo_model_automobilevo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='if_finished',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
