# Generated by Django 4.0.3 on 2022-10-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_serviceappointment_if_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='vip',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
