# Generated by Django 4.0.3 on 2022-10-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_serviceappointment_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='vip',
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
